# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('cartoon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
